# Generated by Django 5.0.1 on 2026-02-04 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
